[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Linux Administration Course"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
no-section-label = true
git-repository-url = "https://github.com/ProfessionalLinuxUsersGroup/lac"
edit-url-template = "https://github.com/ProfessionalLinuxUsersGroup/lac/issues"
git-repository-icon = "fa-github"
